#!/bin/sh
[[ ! -d /config/cron/15min ]] && /bin/mkdir -p /config/cron/15min
[[ ! -d /config/cron/hourly ]] && /bin/mkdir -p /config/cron/hourly
[[ ! -d /config/cron/daily ]] && /bin/mkdir -p /config/cron/daily
[[ ! -d /config/cron/weekly ]] && /bin/mkdir -p /config/cron/weekly
[[ ! -d /config/cron/monthly ]] && /bin/mkdir -p /config/cron/monthly

/bin/rm -rf /etc/periodic/15min/{*,.*}
/bin/rm -rf /etc/periodic/hourly/{*,.*}
/bin/rm -rf /etc/periodic/daily/{*,.*}
/bin/rm -rf /etc/periodic/weekly/{*,.*}
/bin/rm -rf /etc/periodic/monthly/{*,.*}

/bin/cp /defaults/importcrons /etc/periodic/15min/importcrons

[[ -d /config/cron/15min ]] && /bin/cp -R /config/cron/15min/. /etc/periodic/15min/
[[ -d /config/cron/hourly ]] && /bin/cp -R /config/cron/hourly/. /etc/periodic/hourly/
[[ -d /config/cron/daily ]] && /bin/cp -R /config/cron/daily/. /etc/periodic/daily/
[[ -d /config/cron/weekly ]] && /bin/cp -R /config/cron/weekly/. /etc/periodic/weekly/
[[ -d /config/cron/monthly ]] && /bin/cp -R /config/cron/monthly/. /etc/periodic/monthly/

/bin/chmod a+x /etc/periodic/15min/.
/bin/chmod a+x /etc/periodic/hourly/.
/bin/chmod a+x /etc/periodic/daily/.
/bin/chmod a+x /etc/periodic/weekly/.
/bin/chmod a+x /etc/periodic/monthly/.
