#!/bin/sh
echo "[Starting cron import...]" >> /dev/stdout
[[ ! -d /config/cron/15min ]] && /bin/mkdir -p /config/cron/15min
[[ ! -d /config/cron/hourly ]] && /bin/mkdir -p /config/cron/hourly
[[ ! -d /config/cron/daily ]] && /bin/mkdir -p /config/cron/daily
[[ ! -d /config/cron/weekly ]] && /bin/mkdir -p /config/cron/weekly
[[ ! -d /config/cron/monthly ]] && /bin/mkdir -p /config/cron/monthly

/bin/rm -rf /etc/periodic/15min/{*,.*}
/bin/rm -rf /etc/periodic/hourly/{*,.*}
/bin/rm -rf /etc/periodic/daily/{*,.*}
/bin/rm -rf /etc/periodic/weekly/{*,.*}
/bin/rm -rf /etc/periodic/monthly/{*,.*}

/bin/cp /defaults/importcrons /etc/periodic/15min/1
[[ -f /config/cron/15min/1 ]] && /bin/mv /config/cron/15min/1 /config/cron/15min/1a

[[ -d /config/cron/15min ]] && /bin/cp -R /config/cron/15min/. /etc/periodic/15min/
[[ -d /config/cron/hourly ]] && /bin/cp -R /config/cron/hourly/. /etc/periodic/hourly/
[[ -d /config/cron/daily ]] && /bin/cp -R /config/cron/daily/. /etc/periodic/daily/
[[ -d /config/cron/weekly ]] && /bin/cp -R /config/cron/weekly/. /etc/periodic/weekly/
[[ -d /config/cron/monthly ]] && /bin/cp -R /config/cron/monthly/. /etc/periodic/monthly/

/usr/bin/find /etc/periodic/15min/ -type f -exec /bin/chmod a+x {} \;
/usr/bin/find /etc/periodic/hourly/ -type f -exec /bin/chmod a+x {} \;
/usr/bin/find /etc/periodic/daily/ -type f -exec /bin/chmod a+x {} \;
/usr/bin/find /etc/periodic/weekly/ -type f -exec /bin/chmod a+x {} \;
/usr/bin/find /etc/periodic/monthly/ -type f -exec /bin/chmod a+x {} \;
echo "[Completed crom import.]" >> /dev/stdout
