#!/bin/sh
echo "[Begin Cron Imports...]" >> /dev/stdout
[[ ! -d /config/cron/15min ]] && mkdir -p /config/cron/15min
[[ ! -d /config/cron/hourly ]] && mkdir -p /config/cron/hourly
[[ ! -d /config/cron/daily ]] && mkdir -p /config/cron/daily
[[ ! -d /config/cron/weekly ]] && mkdir -p /config/cron/weekly
[[ ! -d /config/cron/monthly ]] && mkdir -p /config/cron/monthly

rm -rf /etc/periodic/15min/{*,.*}
rm -rf /etc/periodic/hourly/{*,.*}
rm -rf /etc/periodic/daily/{*,.*}
rm -rf /etc/periodic/weekly/{*,.*}
rm -rf /etc/periodic/monthly/{*,.*}

cp /defaults/importcrons /etc/periodic/15min/importcrons

[[ -d /config/cron/15min ]] && cp -R /config/cron/15min/. /etc/periodic/15min/
[[ -d /config/cron/hourly ]] && cp -R /config/cron/hourly/. /etc/periodic/hourly/
[[ -d /config/cron/daily ]] && cp -R /config/cron/daily/. /etc/periodic/daily/
[[ -d /config/cron/weekly ]] && cp -R /config/cron/weekly/. /etc/periodic/weekly/
[[ -d /config/cron/monthly ]] && cp -R /config/cron/monthly/. /etc/periodic/monthly/

chmod +x /etc/periodic/15min/*
chmod +x /etc/periodic/hourly/*
chmod +x /etc/periodic/daily/*
chmod +x /etc/periodic/weekly/*
chmod +x /etc/periodic/monthly/*
echo "[Finished Cron Imports.]" >> /dev/stdout
